=begin
#Zodomus channel manager API

#Zodomus is a channel manager API for OTA's access (Booking, Expedia, Airbnb, ...)  # Introduction In this API reference you have a list of Zodomus API's       # Authentication To start using Zodomus you should get your API Keys in the development tab.\\ You will have Test and Production API Keys (only after testing).\\ To access credit card information use you API Key (test or production) with the special **credit card password**. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Zodomus::BookingTablesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BookingTablesApi' do
  before do
    # run before each test
    @api_instance = Zodomus::BookingTablesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BookingTablesApi' do
    it 'should create an instance of BookingTablesApi' do
      expect(@api_instance).to be_instance_of(Zodomus::BookingTablesApi)
    end
  end

  # unit tests for booking_ambiance_types_get
  # Get Booking Ambiance Types
  # Get Booking Ambiance Types
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_ambiance_types_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_breakfast_types_get
  # Get Booking Breakfast Types
  # Get Booking Breakfast Types
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_breakfast_types_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_cancellation_types_get
  # Get Booking Cancellation Types
  # Get Booking Cancellation Types
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_cancellation_types_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_charge_types_get
  # Get Booking Charge Types
  # Get Booking Charge Types
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_charge_types_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_contact_types_get
  # Get Booking Contact Types
  # Get Booking Contact Types
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_contact_types_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_cuisine_types_get
  # Get Booking Cuisine Types
  # Get Booking Cuisine Types
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_cuisine_types_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_dietary_types_get
  # Get Booking Dietary Types
  # Get Booking Dietary Types
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_dietary_types_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_fee_tax_policies_get
  # Get Booking Fee Tax Policies
  # Get Booking Fee Tax Policies
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_fee_tax_policies_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_hotel_amenities_get
  # Get Booking Hotel Amenities
  # Get Booking Hotel Amenities
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_hotel_amenities_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_image_tags_get
  # Get Booking Image Tags
  # Get Booking Image Tags
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_image_tags_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_internet_coverages_get
  # Get Booking Internet Coverages
  # Get Booking Internet Coverages
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_internet_coverages_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_internet_types_get
  # Get Booking Internet Types
  # Get Booking Internet Types
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_internet_types_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_language_codes_get
  # Get Booking Language Codes
  # Get Booking Language Codes
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_language_codes_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_meal_plans_get
  # Get Booking Meal Plans
  # Get Booking Meal Plans
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_meal_plans_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_noshow_types_get
  # Get Booking Noshow Types
  # Get Booking Noshow Types
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_noshow_types_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_parking_properties_get
  # Get Booking Parking Properties
  # Get Booking Parking Properties
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_parking_properties_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_parking_reservations_get
  # Get Booking Parking Reservations
  # Get Booking Parking Reservations
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_parking_reservations_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_parking_types_get
  # Get Booking Parking Types
  # Get Booking Parking Types
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_parking_types_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_payment_types_get
  # Get Booking Payment Types
  # Get Booking Payment Types
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_payment_types_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_pets_allowed_get
  # Get Booking Pets Allowed
  # Get Booking Pets Allowed
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_pets_allowed_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_phone_types_get
  # Get Booking Phone Types
  # Get Booking Phone Types
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_phone_types_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_prepayment_types_get
  # Get Booking Prepayment Types
  # Get Booking Prepayment Types
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_prepayment_types_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_property_types_get
  # Get Booking Property Types
  # Get Booking Property Types
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_property_types_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_restaurant_services_get
  # Get Booking Restaurant Services
  # Get Booking Restaurant Services
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_restaurant_services_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_room_amenities_get
  # Get Booking Room Amenities
  # Get Booking Room Amenities
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_room_amenities_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_room_types_get
  # Get Booking Room Types
  # Get Booking Room Types
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_room_types_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for booking_transportation_codes_get
  # Get Booking Transportation Codes
  # Get Booking Transportation Codes
  # @param [Hash] opts the optional parameters
  # @return [BookingtablesResponse]
  describe 'booking_transportation_codes_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
