=begin
#Zodomus channel manager API

#Zodomus is a channel manager API for OTA's access (Booking, Expedia, Airbnb, ...)  # Introduction In this API reference you have a list of Zodomus API's       # Authentication To start using Zodomus you should get your API Keys in the development tab.\\ You will have Test and Production API Keys (only after testing).\\ To access credit card information use you API Key (test or production) with the special **credit card password**. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Zodomus::BookingReportingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BookingReportingApi' do
  before do
    # run before each test
    @api_instance = Zodomus::BookingReportingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BookingReportingApi' do
    it 'should create an instance of BookingReportingApi' do
      expect(@api_instance).to be_instance_of(Zodomus::BookingReportingApi)
    end
  end

  # unit tests for reporting_misconduct_categories_get
  # Get a list of reporting misconduct categories
  # Get a list of reporting misconduct categories
  # @param channel_id Channel id
  # @param property_id Property id supplied by the channel
  # @param [Hash] opts the optional parameters
  # @return [RoomRatesResponse]
  describe 'reporting_misconduct_categories_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for reporting_post
  # Post a reporting status
  # Post a reporting status (isNoShow, StayChange, guestMisconduct, ccIsInvalid,...)
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'reporting_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
