=begin
#Zodomus channel manager API

#Zodomus is a channel manager API for OTA's access (Booking, Expedia, Airbnb, ...)  # Introduction In this API reference you have a list of Zodomus API's       # Authentication To start using Zodomus you should get your API Keys in the development tab.\\ You will have Test and Production API Keys (only after testing).\\ To access credit card information use you API Key (test or production) with the special **credit card password**. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Zodomus::ExpediaTablesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ExpediaTablesApi' do
  before do
    # run before each test
    @api_instance = Zodomus::ExpediaTablesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExpediaTablesApi' do
    it 'should create an instance of ExpediaTablesApi' do
      expect(@api_instance).to be_instance_of(Zodomus::ExpediaTablesApi)
    end
  end

  # unit tests for expedia_amenity_codes_get
  # Get Expedia Amenity Codes
  # Get Expedia Amenity Codes
  # @param [Hash] opts the optional parameters
  # @return [ExpediatablesResponse]
  describe 'expedia_amenity_codes_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expedia_areas_get
  # Get Expedia Areas
  # Get Expedia Areas
  # @param [Hash] opts the optional parameters
  # @return [ExpediatablesResponse]
  describe 'expedia_areas_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expedia_bedsizes_get
  # Get Expedia Bedsizes
  # Get Expedia Bedsizes
  # @param [Hash] opts the optional parameters
  # @return [ExpediatablesResponse]
  describe 'expedia_bedsizes_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expedia_bedtypes_get
  # Get Expedia Bedtypes
  # Get Expedia Bedtypes
  # @param [Hash] opts the optional parameters
  # @return [ExpediatablesResponse]
  describe 'expedia_bedtypes_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expedia_bedtypesizes_get
  # Get Expedia Bedtypesizes
  # Get Expedia Bedtypesizes
  # @param [Hash] opts the optional parameters
  # @return [ExpediatablesResponse]
  describe 'expedia_bedtypesizes_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expedia_categories_get
  # Get Expedia Categories
  # Get Expedia Categories
  # @param [Hash] opts the optional parameters
  # @return [ExpediatablesResponse]
  describe 'expedia_categories_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expedia_featured_amenities_get
  # Get Expedia Featured Amenities
  # Get Expedia Featured Amenities
  # @param [Hash] opts the optional parameters
  # @return [ExpediatablesResponse]
  describe 'expedia_featured_amenities_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expedia_perstay_fees_get
  # Get Expedia Perstay Fees
  # Get Expedia Perstay Fees
  # @param [Hash] opts the optional parameters
  # @return [ExpediatablesResponse]
  describe 'expedia_perstay_fees_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expedia_room_classes_get
  # Get Expedia Room Classes
  # Get Expedia Room Classes
  # @param [Hash] opts the optional parameters
  # @return [ExpediatablesResponse]
  describe 'expedia_room_classes_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expedia_room_details_get
  # Get Expedia Room Details
  # Get Expedia Room Details
  # @param [Hash] opts the optional parameters
  # @return [ExpediatablesResponse]
  describe 'expedia_room_details_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expedia_room_names_get
  # Get Expedia Room Names
  # Get Expedia Room Names
  # @param [Hash] opts the optional parameters
  # @return [ExpediatablesResponse]
  describe 'expedia_room_names_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expedia_room_types_get
  # Get Expedia Room Types
  # Get Expedia Room Types
  # @param [Hash] opts the optional parameters
  # @return [ExpediatablesResponse]
  describe 'expedia_room_types_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expedia_surcharges_get
  # Get Expedia Surcharges
  # Get Expedia Surcharges
  # @param [Hash] opts the optional parameters
  # @return [ExpediatablesResponse]
  describe 'expedia_surcharges_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expedia_value_addinclusions_corporate_get
  # Get Expedia Value Addinclusions Corporate
  # Get Expedia Value Addinclusions Corporate
  # @param [Hash] opts the optional parameters
  # @return [ExpediatablesResponse]
  describe 'expedia_value_addinclusions_corporate_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expedia_value_addinclusions_get
  # Get Expedia Value Addinclusions
  # Get Expedia Value Addinclusions
  # @param [Hash] opts the optional parameters
  # @return [ExpediatablesResponse]
  describe 'expedia_value_addinclusions_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expedia_views_get
  # Get Expedia Views
  # Get Expedia Views
  # @param [Hash] opts the optional parameters
  # @return [ExpediatablesResponse]
  describe 'expedia_views_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
