=begin
#Zodomus channel manager API

#Zodomus is a channel manager API for OTA's access (Booking, Expedia, Airbnb, ...)  # Introduction In this API reference you have a list of Zodomus API's       # Authentication To start using Zodomus you should get your API Keys in the development tab.\\ You will have Test and Production API Keys (only after testing).\\ To access credit card information use you API Key (test or production) with the special **credit card password**. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Zodomus::MappingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MappingApi' do
  before do
    # run before each test
    @api_instance = Zodomus::MappingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MappingApi' do
    it 'should create an instance of MappingApi' do
      expect(@api_instance).to be_instance_of(Zodomus::MappingApi)
    end
  end

  # unit tests for property_activation_post
  # Activate a channel property with Zodomus
  # Activate a propertyId on the channelId selected.&lt;br&gt;&lt;br&gt; priceModelId should be&lt;br&gt;&lt;br&gt; 1 &#x3D; Maximum / single (Booking only, recommended price by Booking)&lt;br&gt; 2 &#x3D; Derived prices (Booking only)&lt;br&gt; 3 &#x3D; Occupancy (Expedia only, recommended by Expedia)&lt;br&gt; 4 &#x3D; Per day / Length of stay (Booking and Expedia)&lt;br&gt;
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'property_activation_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for property_cancellation_post
  # Cancel a channel property with Zodomus
  # Cancel a channel property with Zodomus
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'property_cancellation_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for property_check_post
  # Check a property with Zodomus
  # Check a property with Zodomus
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'property_check_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for rooms_activation_post
  # Activate the property rooms and rates and map them with Zodomus
  # Activate the property rooms and rates and map them with Zodomus
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'rooms_activation_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for rooms_cancellation_post
  # Cancel property rooms associated with Zodomus
  # Cancel property rooms associated with Zodomus
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'rooms_cancellation_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
