=begin
#Zodomus channel manager API

#Zodomus is a channel manager API for OTA's access (Booking, Expedia, Airbnb, ...)  # Introduction In this API reference you have a list of Zodomus API's       # Authentication To start using Zodomus you should get your API Keys in the development tab.\\ You will have Test and Production API Keys (only after testing).\\ To access credit card information use you API Key (test or production) with the special **credit card password**. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.0

=end

require 'date'

module Zodomus
  class RoomR
    attr_accessor :id

    attr_accessor :name

    attr_accessor :total_price

    attr_accessor :guest_name

    attr_accessor :number_of_guests

    attr_accessor :arrival_date

    attr_accessor :departure_date

    attr_accessor :smoking

    attr_accessor :meal_plan

    attr_accessor :remarks

    attr_accessor :addons

    attr_accessor :cancel_penalties

    attr_accessor :prices

    attr_accessor :price_details

    attr_accessor :price_details_extra

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'total_price' => :'totalPrice',
        :'guest_name' => :'guestName',
        :'number_of_guests' => :'numberOfGuests',
        :'arrival_date' => :'ArrivalDate',
        :'departure_date' => :'departureDate',
        :'smoking' => :'smoking',
        :'meal_plan' => :'mealPlan',
        :'remarks' => :'remarks',
        :'addons' => :'addons',
        :'cancel_penalties' => :'cancelPenalties',
        :'prices' => :'prices',
        :'price_details' => :'priceDetails',
        :'price_details_extra' => :'priceDetailsExtra'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'total_price' => :'String',
        :'guest_name' => :'String',
        :'number_of_guests' => :'String',
        :'arrival_date' => :'String',
        :'departure_date' => :'String',
        :'smoking' => :'String',
        :'meal_plan' => :'String',
        :'remarks' => :'String',
        :'addons' => :'Addon',
        :'cancel_penalties' => :'CancelPenalties',
        :'prices' => :'RoomPrices',
        :'price_details' => :'RoomPriceDetails',
        :'price_details_extra' => :'RoomPriceDetailsExtra'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zodomus::RoomR` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zodomus::RoomR`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'total_price')
        self.total_price = attributes[:'total_price']
      end

      if attributes.key?(:'guest_name')
        self.guest_name = attributes[:'guest_name']
      end

      if attributes.key?(:'number_of_guests')
        self.number_of_guests = attributes[:'number_of_guests']
      end

      if attributes.key?(:'arrival_date')
        self.arrival_date = attributes[:'arrival_date']
      end

      if attributes.key?(:'departure_date')
        self.departure_date = attributes[:'departure_date']
      end

      if attributes.key?(:'smoking')
        self.smoking = attributes[:'smoking']
      end

      if attributes.key?(:'meal_plan')
        self.meal_plan = attributes[:'meal_plan']
      end

      if attributes.key?(:'remarks')
        self.remarks = attributes[:'remarks']
      end

      if attributes.key?(:'addons')
        self.addons = attributes[:'addons']
      end

      if attributes.key?(:'cancel_penalties')
        self.cancel_penalties = attributes[:'cancel_penalties']
      end

      if attributes.key?(:'prices')
        self.prices = attributes[:'prices']
      end

      if attributes.key?(:'price_details')
        self.price_details = attributes[:'price_details']
      end

      if attributes.key?(:'price_details_extra')
        self.price_details_extra = attributes[:'price_details_extra']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          total_price == o.total_price &&
          guest_name == o.guest_name &&
          number_of_guests == o.number_of_guests &&
          arrival_date == o.arrival_date &&
          departure_date == o.departure_date &&
          smoking == o.smoking &&
          meal_plan == o.meal_plan &&
          remarks == o.remarks &&
          addons == o.addons &&
          cancel_penalties == o.cancel_penalties &&
          prices == o.prices &&
          price_details == o.price_details &&
          price_details_extra == o.price_details_extra
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, total_price, guest_name, number_of_guests, arrival_date, departure_date, smoking, meal_plan, remarks, addons, cancel_penalties, prices, price_details, price_details_extra].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        Zodomus.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
