=begin
#Zodomus channel manager API

#Zodomus is a channel manager API for OTA's access (Booking, Expedia, Airbnb, ...)  # Introduction In this API reference you have a list of Zodomus API's       # Authentication To start using Zodomus you should get your API Keys in the development tab.\\ You will have Test and Production API Keys (only after testing).\\ To access credit card information use you API Key (test or production) with the special **credit card password**. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.0

=end

# Common files
require 'zodomus/api_client'
require 'zodomus/api_error'
require 'zodomus/version'
require 'zodomus/configuration'

# Models
require 'zodomus/models/accepted_payment'
require 'zodomus/models/account'
require 'zodomus/models/account_response'
require 'zodomus/models/active_weekdays'
require 'zodomus/models/active_weekdays1'
require 'zodomus/models/additional_dates'
require 'zodomus/models/additional_dates1'
require 'zodomus/models/addon'
require 'zodomus/models/addresses'
require 'zodomus/models/affiliation_info'
require 'zodomus/models/area_info'
require 'zodomus/models/attributes'
require 'zodomus/models/attributes1'
require 'zodomus/models/attributes2'
require 'zodomus/models/attributes3'
require 'zodomus/models/attributes6'
require 'zodomus/models/attributes9'
require 'zodomus/models/availability_request'
require 'zodomus/models/book_date'
require 'zodomus/models/book_date1'
require 'zodomus/models/book_time'
require 'zodomus/models/book_time1'
require 'zodomus/models/bookingtables'
require 'zodomus/models/bookingtables_response'
require 'zodomus/models/cancel_penalties'
require 'zodomus/models/channel'
require 'zodomus/models/channel_response'
require 'zodomus/models/clean'
require 'zodomus/models/comfort'
require 'zodomus/models/contact_info'
require 'zodomus/models/currencies_response'
require 'zodomus/models/customer'
require 'zodomus/models/customer_cc'
require 'zodomus/models/discount'
require 'zodomus/models/early_boker'
require 'zodomus/models/excluded_dates'
require 'zodomus/models/excluded_dates1'
require 'zodomus/models/expediatables'
require 'zodomus/models/expediatables_response'
require 'zodomus/models/facilities'
require 'zodomus/models/facility_info'
require 'zodomus/models/guest_reviews_response'
require 'zodomus/models/hotel_content'
require 'zodomus/models/hotel_info'
require 'zodomus/models/last_minute'
require 'zodomus/models/last_minute1'
require 'zodomus/models/location'
require 'zodomus/models/multimedia_description'
require 'zodomus/models/opportunities_request'
require 'zodomus/models/opportunities_response'
require 'zodomus/models/opportunity'
require 'zodomus/models/opportunity1'
require 'zodomus/models/parent_rate'
require 'zodomus/models/parent_rates'
require 'zodomus/models/parent_rates1'
require 'zodomus/models/policies'
require 'zodomus/models/pricemodel_response'
require 'zodomus/models/prices'
require 'zodomus/models/product_request'
require 'zodomus/models/promotion'
require 'zodomus/models/promotions_request'
require 'zodomus/models/promotions_response'
require 'zodomus/models/property_activation_request'
require 'zodomus/models/property_cancellation_request'
require 'zodomus/models/property_check_request'
require 'zodomus/models/property_request'
require 'zodomus/models/property_status_request'
require 'zodomus/models/rate'
require 'zodomus/models/rate_request'
require 'zodomus/models/rates_derived_request'
require 'zodomus/models/rates_request'
require 'zodomus/models/reporting_request'
require 'zodomus/models/reservation'
require 'zodomus/models/reservation2'
require 'zodomus/models/reservation3'
require 'zodomus/models/reservation4'
require 'zodomus/models/reservations_cc_response'
require 'zodomus/models/reservations_createtest_request'
require 'zodomus/models/reservations_queue_response'
require 'zodomus/models/reservations_response'
require 'zodomus/models/reservations_summary_response'
require 'zodomus/models/review_score'
require 'zodomus/models/reviewer'
require 'zodomus/models/reviews_request'
require 'zodomus/models/reviews_score'
require 'zodomus/models/reviews_score_response'
require 'zodomus/models/room'
require 'zodomus/models/room1'
require 'zodomus/models/room_price_details'
require 'zodomus/models/room_price_details_extra'
require 'zodomus/models/room_prices'
require 'zodomus/models/room_r'
require 'zodomus/models/room_rates_response'
require 'zodomus/models/room_request'
require 'zodomus/models/room_status_request'
require 'zodomus/models/rooms'
require 'zodomus/models/rooms1'
require 'zodomus/models/rooms2'
require 'zodomus/models/rooms3'
require 'zodomus/models/rooms_activation_request'
require 'zodomus/models/rooms_cancellation_request'
require 'zodomus/models/scoring'
require 'zodomus/models/service'
require 'zodomus/models/staff'
require 'zodomus/models/stats'
require 'zodomus/models/status'
require 'zodomus/models/stay_date'
require 'zodomus/models/stay_date1'
require 'zodomus/models/total_revenue'
require 'zodomus/models/tpa_extensions'
require 'zodomus/models/transportation'
require 'zodomus/models/value'
require 'zodomus/models/week_days'

# APIs
require 'zodomus/api/account_and_info_api'
require 'zodomus/api/booking_guest_reviews_api'
require 'zodomus/api/booking_opportunities_api'
require 'zodomus/api/booking_promotions_api'
require 'zodomus/api/booking_reporting_api'
require 'zodomus/api/booking_tables_api'
require 'zodomus/api/content_api'
require 'zodomus/api/expedia_tables_api'
require 'zodomus/api/mapping_api'
require 'zodomus/api/rates_and_availability_api'
require 'zodomus/api/reservation_api'

module Zodomus
  class << self
    # Customize default settings for the SDK using block.
    #   Zodomus.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
